export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const FETCH_CATEGORY_ERROR = 'FETCH_CATEGORY_ERROR';
export const FETCH_IMAGEURL = 'FETCH_IMAGEURL';
export const FETCH_IMAGEURL_ERROR = 'FETCH_IMAGEURL_ERROR';
