export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_ERROR = 'ADD_CATEGORY_ERROR';
export const ADD_IMAGEURL = 'ADD_IMAGEURL';
export const ADD_IMAGEURL_ERROR = 'ADD_IMAGEURL_ERROR';
